name: Deploy Salesforce DX project

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Salesforce CLI
      uses: sfdx-actions/setup-sfdx@v1
      with:
        sfdx-version:: 'latest'
    - name: Authenticate with Salesforce
      run: |
          sfdx force:auth:username:password -u rishabh.zutshi-yuny@force.com -p Zutshicot@23 -r https://login.salesforce.com -a scratchorg
          sfdx force:org:create -s -f config/project-scratch-def.json -a scratchorg

    - name: Deploy metadata to scratch org
      run: |
        sfdx force:source:deploy -p force-app -u scratchorg
