name: Deploy Salesforce DX project

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Salesforce CLI
      uses: sfdx-actions/setup-sfdx@v1
      with:
        version: 'latest'
    - name: Authenticate with Salesforce
      run: |
        sfdx auth login --instanceurl https://login.salesforce.com --setalias scratchorg 
        sfdx force:org:create -s -f config/project-scratch-def.json -a scratchorg
        
    - name: Push metadata to scratch org
      run: |
        sfdx force:source:push -u scratchorg -a scratchorg

